# Generated by Django 3.0.8 on 2020-07-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0008_auto_20200714_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='minutes_after_midnight',
            new_name='minutes_after_midnight_start',
        ),
        migrations.AddField(
            model_name='activity',
            name='minutes_after_midnight_end',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
