# Generated by Django 3.0.8 on 2020-12-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0009_auto_20200721_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_str',
            field=models.CharField(default='0-0-0', max_length=50),
            preserve_default=False,
        ),
    ]
