# Generated by Django 3.0.8 on 2020-12-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0010_activity_date_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_str',
        ),
        migrations.AddField(
            model_name='activity',
            name='date_string',
            field=models.CharField(default='0-Jan-0000', max_length=50),
        ),
    ]
