# Generated by Django 3.0.8 on 2021-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0012_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_category',
            field=models.CharField(default='undefined', max_length=250),
        ),
    ]
