# Generated by Django 3.0.8 on 2021-01-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0013_activity_activity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='unique_id',
            field=models.IntegerField(default=39846),
        ),
    ]
