# Generated by Django 3.0.8 on 2021-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0014_activity_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='unique_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='unique_id',
            field=models.IntegerField(default=973457),
        ),
    ]
