# Generated by Django 3.0.8 on 2021-01-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0017_auto_20210111_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='unique_id',
            field=models.IntegerField(default=869065),
        ),
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(db_index=True, max_length=240)),
                ('time_value', models.CharField(db_index=True, max_length=240)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='databaseInterface.CategoryStats')),
            ],
        ),
    ]
