# Generated by Django 3.0.8 on 2021-01-14 12:48

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0018_auto_20210114_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('attrs', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='keyval',
            name='container',
        ),
        migrations.AlterField(
            model_name='activity',
            name='unique_id',
            field=models.IntegerField(default=853060),
        ),
        migrations.DeleteModel(
            name='CategoryStats',
        ),
        migrations.DeleteModel(
            name='KeyVal',
        ),
    ]
