# Generated by Django 3.0.8 on 2021-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0020_auto_20210114_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='unique_id',
            field=models.IntegerField(default=448992),
        ),
    ]
