# Generated by Django 3.0.8 on 2021-01-15 17:07

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0027_auto_20210115_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='unique_id',
            field=models.IntegerField(default=991540),
        ),
        migrations.AlterField(
            model_name='stats',
            name='data',
            field=jsonfield.fields.JSONField(default='none'),
        ),
    ]
